### ISSUE TITLE
Error whith get() method

### ISSUE THREAD

**Issue by skruglikov** [jsor/carty#1]
![2017-07-31 16 56 43](https://user-images.githubusercontent.com/4284150/28781061-83c99df4-7611-11e7-8103-c628ca871c07.png)
![2017-07-31 16 56 48](https://user-images.githubusercontent.com/4284150/28781060-83c94fd4-7611-11e7-8e17-11d2c15cc018.png)
![2017-07-31 16 56 54](https://user-images.githubusercontent.com/4284150/28781062-83c9e624-7611-11e7-9243-f5c1d18e2f4c.png)

**Comment by jsor** [comment]
Operations on the cart are asynchronous, that means if you add an item you must do following method calls from the `.ready()` method.

```js
cart
    .add({
        id: 'awesome-product',
        label: 'Awesome product',
        price: 5.99,
        quantity: 2
    })
    .ready(function() {
        var item = cart.get('awesome-product');

        console.log(item);
    });
```

You also note, that items are returned as literal objects, eg. 

```
{
    id: 'awesome-product',
    label: 'Awesome product',
    price: 5.99,
    quantity: 2
}
```
