### ISSUE TITLE
Checkout page with carty.

### ISSUE THREAD

**Issue by skruglikov** [jsor/carty#2]
Hi!
Need help with separate checkout page. I try create checkout form with user info and cart list. User info contains payment selector with several option. But if I selected one of payment option, I have message error:
`Uncaught (in promise) Item must be a string or an object with at least an id property.`
`Uncaught Item must be a string or an object with at least an id property.`
When I select payment option carty takes it try as new product add.
Method createItem() triggered an throw.

P.S.: Sorry for my English ;)

**Comment by jsor** [comment]
Hard to say without seeing the actual code. Could you setup a reproducible test case?
